import Head from 'next/head';
import Footer from '../components/Footer';
import HeroSection from '../components/HeroSection';
import Navbar from '../components/Navbar';
import ResumeSection from '../components/ResumeSection';
import WorkSection from '../components/WorkSection';

export default function Home() {
  return (
    <div id="page-container" className="font-sans">
      <Head>
        <title>Pierre Penhard - Rails Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        <HeroSection />
        <ResumeSection />
        <WorkSection />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
